export const bgImages = [
  {
    imageId: 1,
    svgSrc: "",
    coverPic: "/default.png",
    opImage: "/default-op.svg",
  },
  {
    imageId: 2,
    svgSrc: "/miku.svg",
    coverPic: "/miku2.svg",
    opImage: "/miku-op.svg",
  },
  {
    imageId: 3,
    svgSrc: "/nino.svg",
    coverPic: "/nino2.svg",
    opImage: "/nino-op.svg",
  },
  {
    imageId: 4,
    svgSrc: "/bungou.svg",
    coverPic: "/bungou2.svg",
    opImage: "/bungou-op.svg",
  },
  {
    imageId: 5,
    svgSrc: "/hdxd.svg",
    coverPic: "/hdxd2.svg",
    opImage: "/hdxd-op.svg",
  },
  {
    imageId: 6,
    svgSrc: "/hxh.svg",
    coverPic: "/killua.svg",
    opImage: "/hxh-op.svg",
  },
  {
    imageId: 7,
    svgSrc: "/itachi.svg",
    coverPic: "/itachi2.svg",
    opImage: "/itachi-op.svg",
  },
  {
    imageId: 8,
    svgSrc: "/jinchuriki.svg",
    coverPic: "/jinchuriki2.svg",
    opImage: "/jinchuriki-op.svg",
  },
  {
    imageId: 9,
    svgSrc: "/juju.svg",
    coverPic: "/juju2.svg",
    opImage: "/juju-op.svg",
  },
  {
    imageId: 10,
    svgSrc: "/kaneki.svg",
    coverPic: "/kaneki2.svg",
    opImage: "/kaneki-op.svg",
  },
  {
    imageId: 11,
    svgSrc: "/kurumi.svg",
    coverPic: "/kurumi2.svg",
    opImage: "/kurumi-op.svg",
  },
  {
    imageId: 12,
    svgSrc: "/megumin.svg",
    coverPic: "/megumin2.svg",
    opImage: "/megumin-op.svg",
  },
  {
    imageId: 13,
    svgSrc: "/mha.svg",
    coverPic: "/mha2.svg",
    opImage: "/mha-op.svg",
  },
  {
    imageId: 14,
    svgSrc: "/mikasa.svg",
    coverPic: "/mikasa2.svg",
    opImage: "/mikasa-op.svg",
  },
  {
    imageId: 15,
    svgSrc: "/nezuTan.svg",
    coverPic: "/nezutan2.svg",
    opImage: "/nezuTan-op.svg",
  },
  {
    imageId: 16,
    svgSrc: "/aot.svg",
    coverPic: "/aot2.svg",
    opImage: "/aot-op.svg",
  },
  {
    imageId: 17,
    svgSrc: "/sasuke.svg",
    coverPic: "/sasuke2.svg",
    opImage: "/sasuke-op.svg",
  },
  {
    imageId: 18,
    svgSrc: "/solo.svg",
    coverPic: "/solo2.svg",
    opImage: "/solo-op.svg",
  },
  {
    imageId: 19,
    svgSrc: "/zoro.svg",
    coverPic: "/zoro2.svg",
    opImage: "/zoro-op.svg",
  },
  {
    imageId: 20,
    svgSrc: "/team7.svg",
    coverPic: "/team777.svg",
    opImage: "/team7-op.svg",
  },
];
