---
- name: Deploy Docker container from ECR
  hosts: all
  remote_user: ec2-user
  become: true
  collections:
    - community.aws
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible-ssh.pem
  tasks:
    - name: Install amazon-ecr-credential-helper
      package:
        name: amazon-ecr-credential-helper
        state: present

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Configure ECR login
      community.aws.ecr_login:
        region: ap-south-1
      when: not amazon_ecr_credential_helper.pkg.version

    - name: Pull Docker image from ECR
      docker_image:
        name: 065642457853.dkr.ecr.ap-south-1.amazonaws.com/noteflix:8d315bb4687824af3885686e0b19227d2b128eba
        source: pull

    - name: Run Docker container
      docker_container:
        name: noteflix
        image: 065642457853.dkr.ecr.ap-south-1.amazonaws.com/noteflix:8d315bb4687824af3885686e0b19227d2b128eba
        ports:
          - "3000:3000"
        detach: true
