---
- name: Deploy Docker container from ECR
  hosts: all
  remote_user: ec2-user
  become: true
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible-ssh.pem
  tasks:
    - name: Install AWS CLI
      package:
        name: awscli
        state: present

    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Log in to Amazon ECR
      shell: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin https://065642457853.dkr.ecr.ap-south-1.amazonaws.com

    - name: Pull Docker image from ECR
      docker_image:
        name: 065642457853.dkr.ecr.ap-south-1.amazonaws.com/noteflix:8d315bb4687824af3885686e0b19227d2b128eba
        source: pull

    - name: Run Docker container
      docker_container:
        name: noteflix
        image: 065642457853.dkr.ecr.ap-south-1.amazonaws.com/noteflix:8d315bb4687824af3885686e0b19227d2b128eba
        ports:
          - "3000:3000"
        detach: true
