---
- name: Deploy Docker container from ECR
  hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    aws_region: "ap-south-1"
    ecr_registry: "065642457853.dkr.ecr.ap-south-1.amazonaws.com"
    ecr_image_name: "noteflix"
    ecr_image_tag: "8d315bb4687824af3885686e0b19227d2b128eba"
    docker_container_name: "noteflix"
    docker_port_mapping: "3000:3000"

  tasks:
    - name: Configure AWS credentials using aws configure
      shell: "aws configure set aws_access_key_id {{ lookup('env', 'AWS_ACCESS_KEY_ID') }} && aws configure set aws_secret_access_key {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} && aws configure set region {{ aws_region }}"
      changed_when: false

    - name: Log in to AWS ECR
      shell: "aws ecr get-login-password --region {{ aws_region }}"
      register: ecr_login
      changed_when: false

    - name: Install docker dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - curl
          - gnupg
        state: latest

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/amazonlinux/gpg | sudo gpg --import -
      become: yes

    - name: Add Docker repository
      shell: echo -e "[docker]\nname=Docker Stable - $basearch\nbaseurl=https://download.docker.com/linux/centos/7/$basearch/stable\ngpgcheck=1\ngpgkey=https://download.docker.com/linux/amazonlinux/gpg\nenabled=1\n" | sudo tee /etc/yum.repos.d/docker.repo
      become: yes

    - name: Install Docker engine
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Authenticate Docker with AWS ECR
      docker_login:
        registry_url: "{{ ecr_registry }}"
        username: AWS
        password: "{{ ecr_login.stdout }}"

    - name: Pull Docker image from AWS ECR
      docker_image:
        name: "{{ ecr_registry }}/{{ ecr_image_name }}:{{ ecr_image_tag }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ ecr_registry }}/{{ ecr_image_name }}:{{ ecr_image_tag }}"
        state: started
        ports:
          - "{{ docker_port_mapping }}"
