name: Terraform Provisioning & Conf Management with Ansible

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-south-1

jobs:
  provision_deploy:
    name: Terraform Provision & Deploy Application
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform/remote-provisioning

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set SSH keys & permissions
        run: |
          touch ~/.ssh/id_rsa
          touch ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_ID_RSA }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
          chmod 644 /home/runner/work/Noteflix-v.2/Noteflix-v.2/ansible/inventory.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Set EC2 IP as GitHub Actions Environment Variable
        run: export "EC2_IP=$(terraform output -raw ec2_public_ip)"

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Deploy Application
        run: ansible-playbook -i ./ansible/inventory.py ./ansible/deploy_container.yaml